# February 25, 2015
# https://github.com/bevry/base
language: node_js
# ensure dev dependencies are installed (handled via npm install)
# ensure test dependencies are installed (handled via cake install)
install: "npm install && ./node_modules/.bin/cake install"
# ensure our application is compiled before we run our tests
before_script: "./node_modules/.bin/cake compile"
script: "npm test"
node_js:
  - "0.12"
  - "stable"
cache:
  directories:
    - node_modules
